In [1]:
import numpy as np
import pandas as pd

# # 데이터 전처리
---

In [3]:
df = pd.read_csv('/data/NIA50/50-1/data/Sejong/0901_5RNBVU80.csv')
df.loc[df['scene'].]

,ISSUE_DATE,VEHICLE_CLASS,VEHICLE_TYPE,X,Y,HEADING,SPEED,HAZARDLIGHTS_FLAG,HARDBRAKING_FLAG,LIGHTSCHANGE_FLAG,HARDDECELERATION_FLAG,UTURN_FLAG,LIGHTS_STATUS,CURRENT_LANE,scene,Turn,Change,Speed,Hazard
0,2022-09-01 08:54:26,9220.0,4.0,127.393805,36.410704,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,scene_0,NaN,NaN,NaN,False
1,2022-09-01 08:54:27,9220.0,4.0,127.393509,36.410776,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,scene_0,NaN,NaN,NaN,False
2,2022-09-01 08:54:28,9220.0,4.0,127.393214,36.410849,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,scene_0,NaN,NaN,NaN,False
3,2022-09-01 08:54:29,9220.0,4.0,127.392864,36.410941,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,scene_0,NaN,NaN,NaN,False
4,2022-09-01 08:54:50,9220.0,4.0,127.386428,36.412362,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,scene_3,NaN,NaN,NaN,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13319,2022-09-01 14:32:35,9220.0,4.0,127.390315,36.411552,30.0,-5.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,scene_2029,Right,NaN,NaN,False
13320,2022-09-01 14:32:36,9220.0,4.0,127.390614,36.411471,28.0,-5.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,scene_2029,Right,NaN,NaN,False
13321,2022-09-01 14:32:37,9220.0,4.0,127.390903,36.411394,24.0,-9.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,scene_2029,Right,NaN,NaN,False
13322,2022-09-01 14:32:38,9220.0,4.0,127.391184,36.411320,23.0,-10.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,scene_2029,Right,NaN,NaN,False
13323,2022-09-01 14:32:39,9220.0,4.0,127.391184,36.411320,21.0,-9.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,scene_2029,Right,NaN,NaN,False

In [41]:
# (samples, features, time)
scenes.value_counts()[scenes.value_counts() < 10]

scene_4    4
Name: scene, dtype: int64